"""tambah role super admin

Revision ID: 1a2599386c62
Revises: 
Create Date: 2025-08-18 08:16:49.714899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a2599386c62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_statistics_display_order', table_name='statistics')
    op.drop_index('ix_statistics_title', table_name='statistics')
    op.drop_table('statistics')
    # ### end Alembic commands ###
    
    # Add SUPER_ADMIN to UserRole enum
    op.execute("ALTER TYPE userrole ADD VALUE 'SUPER_ADMIN' BEFORE 'ADMIN'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stats', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='statistics_pkey')
    )
    op.create_index('ix_statistics_title', 'statistics', ['title'], unique=False)
    op.create_index('ix_statistics_display_order', 'statistics', ['display_order'], unique=False)
    # ### end Alembic commands ###
