"""empty message

Revision ID: 385658b8df96
Revises: 7909f7a49c0c
Create Date: 2025-08-12 01:21:32.905004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '385658b8df96'
down_revision: Union[str, None] = '7909f7a49c0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if indexes exist before dropping them
    connection = op.get_bind()
    
    # Check if ix_statistics_display_order exists
    result = connection.execute(sa.text("""
        SELECT 1 FROM pg_indexes 
        WHERE tablename = 'statistics' AND indexname = 'ix_statistics_display_order'
    """))
    if result.fetchone():
        op.drop_index('ix_statistics_display_order', table_name='statistics')
    
    # Check if ix_statistics_title exists
    result = connection.execute(sa.text("""
        SELECT 1 FROM pg_indexes 
        WHERE tablename = 'statistics' AND indexname = 'ix_statistics_title'
    """))
    if result.fetchone():
        op.drop_index('ix_statistics_title', table_name='statistics')
    
    # Check if statistics table exists before dropping
    result = connection.execute(sa.text("""
        SELECT 1 FROM pg_tables WHERE tablename = 'statistics'
    """))
    if result.fetchone():
        op.drop_table('statistics')
    
    # Add name column as nullable first
    op.add_column('rpp_submission_items', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('rpp_submission_items', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Update existing records with default names
    op.execute("""
        UPDATE rpp_submission_items 
        SET name = COALESCE(
            (SELECT 'RPP File - ' || mf.file_name FROM media_files mf WHERE mf.id = rpp_submission_items.file_id),
            'RPP Item #' || rpp_submission_items.id::text
        )
        WHERE name IS NULL;
    """)
    
    # Make name column NOT NULL after updating existing records
    op.alter_column('rpp_submission_items', 'name', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rpp_submission_items', 'description')
    op.drop_column('rpp_submission_items', 'name')
    op.create_table('statistics',
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stats', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='statistics_pkey')
    )
    op.create_index('ix_statistics_title', 'statistics', ['title'], unique=False)
    op.create_index('ix_statistics_display_order', 'statistics', ['display_order'], unique=False)
    # ### end Alembic commands ###
