"""add org order

Revision ID: 65f85f6158fe
Revises: 1a2599386c62
Create Date: 2025-08-21 00:50:14.099772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65f85f6158fe'
down_revision: Union[str, None] = '1a2599386c62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_statistics_display_order', table_name='statistics')
    op.drop_index('ix_statistics_title', table_name='statistics')
    op.drop_table('statistics')
    
    # Add display_order column as nullable first
    op.add_column('organizations', sa.Column('display_order', sa.Integer(), nullable=True))
    
    # Set default values for existing organizations using a different approach
    op.execute("""
        WITH ordered_orgs AS (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at) as new_order
            FROM organizations 
            WHERE display_order IS NULL
        )
        UPDATE organizations 
        SET display_order = ordered_orgs.new_order
        FROM ordered_orgs
        WHERE organizations.id = ordered_orgs.id
    """)
    
    # Make the column NOT NULL
    op.alter_column('organizations', 'display_order', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'display_order')
    op.create_table('statistics',
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stats', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('img_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('display_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='statistics_pkey')
    )
    op.create_index('ix_statistics_title', 'statistics', ['title'], unique=False)
    op.create_index('ix_statistics_display_order', 'statistics', ['display_order'], unique=False)
    # ### end Alembic commands ###
